//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XKARTEntities : DbContext
    {
        public XKARTEntities()
            : base("name=XKARTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESSes { get; set; }
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<KART> KARTs { get; set; }
        public virtual DbSet<ORDERHISTORY> ORDERHISTORies { get; set; }
        public virtual DbSet<ORDERPLACED> ORDERPLACEDs { get; set; }
        public virtual DbSet<PREVISIT> PREVISITs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCTDESCRIPTION> PRODUCTDESCRIPTIONs { get; set; }
        public virtual DbSet<PRODUCTPICTURE> PRODUCTPICTUREs { get; set; }
        public virtual DbSet<SEARCHISTORY> SEARCHISTORies { get; set; }
        public virtual DbSet<SELLER> SELLERs { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TREND> TRENDS { get; set; }
    }
}
