//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERHISTORY
    {
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long CustomerId { get; set; }
        public long Quantity { get; set; }
        public long Amount { get; set; }
        public long AddressId { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ORDERPLACED ORDERPLACED { get; set; }
    }
}
