//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERPLACED
    {
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long CustomerId { get; set; }
        public long Quantity { get; set; }
        public long Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string PaymentType { get; set; }
        public long AddressId { get; set; }
        public string Status { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ORDERHISTORY ORDERHISTORY { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
