//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTPICTURE
    {
        public long PictureId { get; set; }
        public long ProductId { get; set; }
        public string PicturePath { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
