//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amazon
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCHISTORY
    {
        public long SearchId { get; set; }
        public long CustomerId { get; set; }
        public string SearchTag { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
